[build]
  command = "pip install -r requirements.txt && npm install && npm run build"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
