services:
  - type: web
    name: signaturepro
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
